{
  stateVersion,
  ...
}:
{
  imports = [
    ./hardware-configuration.nix
    ./frigate.nix
    ./nvidia.nix
    ./cuda-onnxruntime.nix
    ../../../profiles/adsb-hub.nix
  ];

  networking.hostName = "nvrhub";

  system.stateVersion = stateVersion;

  ###########################################
  # Surveillance media storage
  ###########################################
  #
  # 4 TB WD Purple (WD40PURZ, a surveillance-class drive) dedicated to NVR
  # recordings. Deliberately NOT declared in hardware-configuration.nix: that
  # file is generated by nixos-generate-config and carries a "do not modify"
  # header, whereas this mount is a deliberate architectural choice.
  #
  # XFS rather than ext4 (the rest of the fleet) or btrfs. The workload is
  # large sequential writes from 8 cameras, continuously, forever:
  #
  #   * XFS's allocation groups (4 here) let concurrent camera writers append
  #     without contending on a single allocator, and delayed allocation keeps
  #     extents large, which is what limits fragmentation on an append-only
  #     video store. Metadata is CRC-protected (crc=1).
  #   * btrfs was rejected specifically because its data checksums -- the only
  #     reason to prefer it here -- cannot coexist with this workload. CoW
  #     fragments continuous video writes badly, the remedy is nodatacow, and
  #     nodatacow also disables data checksumming. The feature that justified
  #     the choice is the feature you have to turn off.
  #   * XFS cannot shrink. Irrelevant: this is a whole-disk media volume that
  #     only ever grows or gets replaced.
  #
  # Referenced by LABEL, not UUID, unlike the root/boot entries. The drive has
  # 69,224 power-on hours (7.9 years) and takes continuous writes, so it is
  # the single most likely component in this fleet to need replacing. A label
  # means a replacement drive is adopted by labelling it `nvr-media` at mkfs
  # time, with no edit to this file; a UUID would hardcode the identity of a
  # disk that is expected to die.
  fileSystems."/var/lib/frigate" = {
    device = "/dev/disk/by-label/nvr-media";
    fsType = "xfs";
    options = [
      # Recordings are written once and read by timestamp; access times are
      # pure write amplification on a spinning surveillance disk.
      "noatime"

      # Boot must not block on this disk.
      #
      # Without nofail, a dead or unplugged media drive makes systemd fail the
      # local-fs.target dependency chain and drops the box to an emergency
      # shell -- unreachable over SSH, so the one machine that could tell you
      # the disk died is also the one you cannot log into. That is the worst
      # possible failure mode for a headless host in a closet.
      #
      # With nofail the host boots, stays reachable, and node_exporter keeps
      # reporting -- so the monitoring stack reports the fault instead of the
      # host simply vanishing.
      #
      # NOTE: nofail means a missing disk no longer stops activation, so
      # something else must stop Frigate writing recordings into the root
      # filesystem when the media disk is absent. See the RequiresMountsFor
      # guard below, which is what makes this safe.
      "nofail"
    ];
  };

  # Ownership of the mounted filesystem is deliberately NOT set here.
  #
  # A freshly-mkfs'd XFS root directory is root:root 0755, which the
  # unprivileged `frigate` system user cannot write to. It does not need a
  # manual chown: the upstream unit sets StateDirectory=frigate with
  # StateDirectoryMode=0750, and per systemd.exec(5) systemd chowns the
  # innermost directory to User=/Group= and chmods it to that mode on every
  # start whenever the current owner does not match. Because this mount lands
  # exactly on /var/lib/frigate, systemd fixes up the XFS root directory
  # itself. A tmpfiles rule or an activation-script chown here would be
  # redundant and would fight systemd for ownership of the same path.
  #
  # That chown is RECURSIVE when ownership does not match, which makes start
  # ordering load-bearing: when services.frigate is enabled it MUST also carry
  #
  #   systemd.services.frigate.unitConfig.RequiresMountsFor = "/var/lib/frigate";
  #
  # because `nofail` above lets the host boot with this disk missing. Without
  # that guard StateDirectory= would create /var/lib/frigate on the ROOT
  # filesystem and record into it -- 8 cameras at ~7.9 Mbps fill the 465 GB
  # root disk in under a day, and mounting the media disk later hides that
  # footage without deleting it. The guard is not added here on purpose: it
  # would materialise a stub frigate.service with no ExecStart.

  # fsck.xfs and the kernel driver must exist in the initrd/system closure for
  # the mount above to be checkable and mountable.
  boot.supportedFilesystems = [ "xfs" ];
}
