# SyncClipboard desktop client, pointed at the sdrhub clipboard server.
#
# The client keeps its own state in ~/.config/SyncClipboard/SyncClipboard.json
# and rewrites that file whenever a setting changes in the UI, so the file
# cannot be a read-only symlink into the store. Instead a pre-start step merges
# the connection settings into whatever is already there, which keeps the
# server details declarative while leaving every other key under the app's
# control.
#
# The password necessarily ends up in that JSON in plaintext, because that is
# where the client reads it from. It arrives from sops rather than the Nix
# store (which is world-readable), and the file is left mode 0600.
{
  lib,
  pkgs,
  config,
  user,
  ...
}:
let
  cfg = config.desktop.clipboard;

  # Same secret the server container consumes, referenced rather than copied so
  # the two cannot drift apart. It is an env-format file:
  #   SYNCCLIPBOARD_USERNAME=...
  #   SYNCCLIPBOARD_PASSWORD=...
  secretKey = "docker/sdrhub/syncclipboard.env";

  configure = pkgs.writeShellApplication {
    name = "syncclipboard-configure";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      secret="${config.sops.secrets.${secretKey}.path}"
      target="$HOME/.config/SyncClipboard/SyncClipboard.json"

      mkdir -p "$(dirname "$target")"
      [ -f "$target" ] || echo '{}' > "$target"

      username="$(sed -n 's/^SYNCCLIPBOARD_USERNAME=//p' "$secret")"
      password="$(sed -n 's/^SYNCCLIPBOARD_PASSWORD=//p' "$secret")"

      if [ -z "$username" ] || [ -z "$password" ]; then
        echo "syncclipboard: credentials missing from $secret" >&2
        exit 1
      fi

      # A stable account id rather than the GUID the UI would generate, so that
      # re-running this updates the same account instead of accumulating one
      # per activation. The id is only ever a dictionary key.
      tmp="$(mktemp)"
      jq \
        --arg url ${lib.escapeShellArg cfg.serverUrl} \
        --arg user "$username" \
        --arg pass "$password" \
        '.SavedAccounts.SyncClipboard.sdrhub = {
            RemoteURL: $url,
            UserName: $user,
            Password: $pass,
            DeletePreviousFilesOnPush: true,
            CustomName: "sdrhub"
          }
          | .Account = { AccountId: "sdrhub", AccountType: "SyncClipboard" }
          | .SyncService.SyncSwitchOn = true

          # Force the client onto wl-clipboard by forbidding the other two
          # sources. This is half of a two-part fix and is useless on its own:
          # the overlay has to supply the wl-clipboard binary as well, or
          # prohibiting the alternatives leaves the client with nothing.
          #
          # Left to itself the client prefers Avalonia its own in-process X11
          # path, which only sees the Wayland selection via XWayland. That
          # returns content for some copies and nothing for others, and an
          # empty read is classified as `Unkown` and dropped without an error.
          # Symptom is intermittent syncing, not an obvious failure.
          | .ClipboardFactory.ProhibitSources = ["xclip", "Avalonia"]

          # Server-side history is the reason this service exists at all, and
          # it is off by default -- local history alone would leave the panel
          # disagreeing with what the server holds.
          | .History.EnableHistory = true
          | .History.EnableSyncHistory = true

          | .Program.Language = "en-US"
          | .Program.HideWindowOnStartup = true' \
        "$target" > "$tmp"

      mv "$tmp" "$target"
      chmod 600 "$target"
    '';
  };
in
{
  options.desktop.clipboard = {
    enable = lib.mkEnableOption "SyncClipboard client";

    serverUrl = lib.mkOption {
      type = lib.types.str;
      # HTTPS, on a name a public CA can issue for.
      #
      # This client sends HTTP Basic credentials on every request, and the
      # payload is whatever was on a clipboard -- so both the password below
      # and the clipboard contents used to cross the LAN in plaintext. That
      # is a much worse trade than it looks next to the other sdrhub vhosts,
      # none of which carry either.
      #
      # Nothing has to be installed on the client for this to work. The
      # certificate is a genuine Let's Encrypt wildcard obtained over DNS-01
      # (see hosts/linux/sdrhub/acme.nix), so it validates against the trust
      # store every machine already has -- which is precisely why this was
      # not done with a private CA.
      #
      # Reverting this one line is NOT a clean rollback, so do not treat it as
      # one. `clipboard.sdrhub.lan` is no longer served in parallel: it is
      # generated by `legacyRedirectVirtualHosts` in
      # hosts/linux/sdrhub/configuration.nix and its only location returns
      # `308 https://clipboard.int.fredsystems.org$request_uri`. Reverting
      # therefore lands on an untested path that depends on the client following
      # a redirect with method and body intact -- and, worse, sends the Basic
      # credential in the clear on the first hop before the redirect is even
      # read. A real rollback means restoring the plaintext proxy in that vhost.
      default = "https://clipboard.int.fredsystems.org";
      description = "Base URL of the SyncClipboard server.";
    };
  };

  config = lib.mkIf cfg.enable {
    users.users.${user}.packages = [ pkgs.syncclipboard ];

    sops.secrets.${secretKey} = {
      owner = user;
      mode = "0400";
    };

    # Tray-only application, so it needs a running graphical session with an
    # SNI host (wayle provides the StatusNotifierWatcher on this fleet).
    systemd.user.services.syncclipboard = {
      description = "SyncClipboard client";
      partOf = [ "graphical-session.target" ];
      after = [ "graphical-session.target" ];
      wantedBy = [ "graphical-session.target" ];
      serviceConfig = {
        Type = "simple";
        ExecStartPre = lib.getExe configure;
        ExecStart = lib.getExe pkgs.syncclipboard;
        Restart = "always";
        RestartSec = "5s";
      };
    };
  };
}
